# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
