# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc_biallelic_cpp <- function(args) {
    .Call('_MALECOT_run_mcmc_biallelic_cpp', PACKAGE = 'MALECOT', args)
}

GTI_posterior_K_sim_cpp <- function(args) {
    .Call('_MALECOT_GTI_posterior_K_sim_cpp', PACKAGE = 'MALECOT', args)
}

GTI_integrated_K_sim_cpp <- function(args) {
    .Call('_MALECOT_GTI_integrated_K_sim_cpp', PACKAGE = 'MALECOT', args)
}

generate_scaffolds_multiallelic_cpp <- function(args) {
    .Call('_MALECOT_generate_scaffolds_multiallelic_cpp', PACKAGE = 'MALECOT', args)
}

run_mcmc_multiallelic_cpp <- function(args) {
    .Call('_MALECOT_run_mcmc_multiallelic_cpp', PACKAGE = 'MALECOT', args)
}

fix_labels_cpp <- function(args_model) {
    .Call('_MALECOT_fix_labels_cpp', PACKAGE = 'MALECOT', args_model)
}

GTI_evidence_sim_cpp <- function(args) {
    .Call('_MALECOT_GTI_evidence_sim_cpp', PACKAGE = 'MALECOT', args)
}

call_hungarian_cpp <- function(args) {
    .Call('_MALECOT_call_hungarian_cpp', PACKAGE = 'MALECOT', args)
}

